- name: GitHub Sync to Upstream Repository
  uses: Jai-JAP/sync-upstream-repo@v1.4.0
  with:
    upstream_repo: "https://github.com/nb557/plugins.git"
    upstream_branch: "main"
    downstream_branch: "main"
    token: ${{ secrets.GITHUB_TOKEN }}
    merge_args: "--strategy-option ours"
