name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:     

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} 

    steps:
      # Шаг 1: Клонируем ваш форк
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Важно для полной истории

      # Шаг 2: Добавляем upstream репозиторий
      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/nb557/plugins.git
          git fetch upstream

      # Шаг 3: Сливаем изменения
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -X theirs || true
          
      # Шаг 4: Пушим обратно в ваш форк
      - name: Push changes
        run: |
          git push origin main
